import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:get/get.dart';
import 'package:reviews_app/bindings/general_bindings.dart';
import 'package:reviews_app/routes/app_pages.dart';
import 'package:reviews_app/utils/constants/colors.dart';
import 'features/personalization/controllers/settings_controller.dart';
import 'localization/app_localizations.dart';
import 'data/services/localization/localization_service.dart';
import 'utils/constants/text_strings.dart';
import 'utils/theme/app_theme.dart';

/// -- Use this class to setup themes, initial Bindings,
/// any animations and much more.
class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    /// -- Initialize Settings controller to load theme mode from local Storage on app launch
    /// and change it when change theme mode button tapped in [SettingsScreen()].
    // final localizationService = Get.put(LocalizationService());
    final localizationService = LocalizationService.instance;
    final controller = Get.put(SettingsController());

    return Obx(
      () => GetMaterialApp(
        navigatorKey: Get.key,
        title: AppTexts.appName,
        debugShowCheckedModeBanner: false,
        theme: AppTheme.lightTheme,
        darkTheme: AppTheme.darkTheme,
        themeMode: controller.themeMode,
        initialBinding: GeneralBindings(),
        getPages: AppPages.pages,
        fallbackLocale: Locale('ar', 'SA'),
        locale: localizationService.currentLocale,
        supportedLocales: localizationService.supportedLocales,
        // textDirection: localizationService.textDirection,
        localizationsDelegates: const [
          // App-specific localization delegate[s] here
          // Generated by intl_utils package
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        home: const Scaffold(
          backgroundColor: AppColors.primaryColor,
          body: Center(
            child: CircularProgressIndicator(color: AppColors.white),
          ),
        ),
      ),
    );
  }
}


/*
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:get/get.dart';
import 'package:reviews_app/bindings/general_bindings.dart';
import 'package:reviews_app/routes/app_pages.dart';
import 'package:reviews_app/utils/constants/colors.dart';
import 'package:reviews_app/utils/localization/localization_service.dart';
import 'features/personalization/controllers/settings_controller.dart';
import 'l10n/app_localizations.dart';
import 'utils/constants/text_strings.dart';
import 'utils/theme/app_theme.dart';

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    final localizationService = Get.put(LocalizationService());

    return Obx(
      () => GetMaterialApp(
        title: AppTexts.appName,
        debugShowCheckedModeBanner: false,
        theme: AppTheme.lightTheme,
        darkTheme: AppTheme.darkTheme,
        themeMode: SettingsController.instance.themeMode,
        initialBinding: GeneralBindings(),
        getPages: AppPages.pages,
        
        // Localization setup
        locale: localizationService.currentLocale,
        supportedLocales: localizationService.supportedLocales,
        localizationsDelegates: const [
          AppLocalizations.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        
        home: const Scaffold(
          backgroundColor: AppColors.primaryColor,
          body: Center(
            child: CircularProgressIndicator(color: AppColors.white),
          ),
        ),
      ),
    );
  }
}


 */