// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDofXbEoBBQdrfetRh5VlyQQWdJme2MZiM',
    appId: '1:188469720407:web:14feef69edda669bcf3a12',
    messagingSenderId: '188469720407',
    projectId: 'places-edd54',
    authDomain: 'places-edd54.firebaseapp.com',
    storageBucket: 'places-edd54.firebasestorage.app',
    measurementId: 'G-N2B9DVKYGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsvFsc98pH0uvmgWs8H56fEZmPiI5Oti8',
    appId: '1:188469720407:android:b95c8a63c382a46bcf3a12',
    messagingSenderId: '188469720407',
    projectId: 'places-edd54',
    storageBucket: 'places-edd54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVpTXxxLiHtIeaCJ7yxdQFEiXleBAE3b0',
    appId: '1:188469720407:ios:06f25486c5810378cf3a12',
    messagingSenderId: '188469720407',
    projectId: 'places-edd54',
    storageBucket: 'places-edd54.firebasestorage.app',
    iosBundleId: 'com.example.reviewsApp',
  );
}
